### ISSUE TITLE
Sinalunga link a css ed immagini (e togliere javascript)

### ISSUE THREAD

**Issue by pbenoli** [pbenoli/ToscanaGit#21]

**Comment by Maurizio-Zucchelli** [comment]
Salve prof, adesso provvederò a togliere javascript (me lo mette in
automatico)

Il Ven 20 Mar 2020, 10:33 pbenoli <notifications@github.com> ha scritto:

**Comment by pbenoli** [comment]
Ma "chi" te lo mette in automatico? Immagino il programma che usi per creare le pagine, quindi la domanda è: che programma usi per creare le pagine?

**Comment by Maurizio-Zucchelli** [comment]
Avendo l'antivirus "Kaspersky" installato nel computer, appena vado a
creare o modificare una pagina HTML, in automatico Kaspersky mi aggiunge
javascript ma non so per quale motivo. Comunque il programma che uso per
creare le pagine si chiama "Visual Studio Code"

Il giorno ven 20 mar 2020 alle ore 19:11 pbenoli <notifications@github.com>
ha scritto:

**Comment by pbenoli** [comment]
Ma se lo togli "a mano" e poi ci lavori, lo riaggiunge?

**Comment by Maurizio-Zucchelli** [comment]
Teoricamente non lo riaggiunge

Il Sab 21 Mar 2020, 08:07 pbenoli <notifications@github.com> ha scritto:
